image: elixir

stages:
  - test
  - deploy

before_script:
  - mix local.hex --force
  - mix deps.get && mix deps.compile

lines_length:
  before_script:
    - 'true'
  script:
    - >
      curl https://gitlab.com/s4m/checks/raw/master/check_lines_length.sh |
      bash -s -- 80 'mix\.lock'

git_history:
  before_script:
    - 'true'
  script:
    - >
      curl https://gitlab.com/s4m/checks/raw/master/check_git_history.sh |
      bash

dogma:
  script:
    - mix dogma

credo:
  script:
    - mix credo --strict

test:
  script:
    - mix test

nxredirect:
  stage: deploy
  script:
    - MIX_ENV=prod mix escript.build
  artifacts:
    paths:
      - nxredirect
    name: "$CI_BUILD_NAME"
