image: elixir

before_script:
  - mix local.hex --force
  - mix deps.get && mix deps.compile

dogma:
  script:
    - mix dogma

credo:
  script:
    - mix credo --strict

test:
  script:
    - mix test

lines_length:
  before_script:
    - 'true'
  script:
    - >
      curl https://gitlab.com/s4m/checks/raw/master/check_lines_length.sh |
      bash -s -- 80 'mix\.lock'

git_history:
  before_script:
    - 'true'
  script:
    - >
      curl https://gitlab.com/s4m/checks/raw/master/check_git_history.sh |
      bash
